"""empty message

Revision ID: 18035a93311b
Revises: ac384c64b9eb
Create Date: 2019-03-15 15:57:26.704620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18035a93311b'
down_revision = 'ac384c64b9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.add_column('roles', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('roles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    op.drop_column('roles', 'name')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    op.drop_column('roles', 'title')
    op.drop_column('roles', 'date_posted')
    op.drop_column('roles', 'content')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
